import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { TheHeader } from '@/components/TheHeader'
import { TheFooter } from '@/components/TheFooter'
import * as React from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    
    <html lang="en">
      <body className='h-screen'>
        
          <TheHeader/>
            <main>
              {children}
            </main>
        <TheFooter/>

      </body>
    </html>
    
  )
}
