import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import {Input} from "@nextui-org/react";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function CatalogLayout({
  children,
}: {
  children: React.ReactNode
}) {
    const button_category = ['JACKETS','BLAZERS','SHIRTS','T-SHIRTS | SWEATSHIRTS','KNITWEAR','TROUSERS']
    

    return (
        <div>
            <div className='flex row  justify-between '>

                <div className='flex justify-evenly m-10 w-1/5 flex-wrap ml-60'>
                    {button_category.map((b)=>(
                        <Link href={`/catalog/${b.replace(' ','')}`} key={b}><button className='border p-2 text-sm mt-2'>{b}</button></Link>
                    ))}
                </div>

            
                <div className='flex items-center mr-60'>
                    <input type="text" />
                </div>
            </div>

            {children}
        </div>
    )
}